clear all; clc; format long; close all; 


%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\ASUS\Desktop\NUMERICAL METHODS IN ENGINEERING\matlap coding\lecture3\Book1.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 04-Dec-2024 18:20:58

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 51);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:AY50";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41", "VarName42", "VarName43", "VarName44", "VarName45", "VarName46", "VarName47", "VarName48", "VarName49", "VarName50", "VarName51"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
Book1 = readtable("C:\Users\ASUS\Desktop\NUMERICAL METHODS IN ENGINEERING\matlap coding\lecture3\Book1.xlsx", opts, "UseExcel", false);

%% Convert to output type
Book1 = table2array(Book1);

%% Clear temporary variables
clear opts
n = size(Book1,1);

for i = 1 : n 
    for j = 1 :n
        a(i,j) = Book1(i,j);
    end
end
for i = 1:n
    c(i) = Book1(i,n+1);
end

for k = 1 : n-1 
    for i = k+1 : n
        m(i,k) = a(i,k) / a(k,k);
        for j = k+1 : n
            a(i,j) = a(i,j) - m(i,k)*a(k,j);
        end
        c(i) = c(i) - m(i,k)*c(k);
    end
end

for k = n : -1 : 1
    sum = 0 ;
    for j = k+1 : n
        sum = sum + a(k,j) * x(j);
    end
    x(k) = (c(k)-sum) / a(k,k);
end
xlswrite('Book1.xlsx',x(:),'x')