%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\ASUS\Desktop\NUMERICAL METHODS IN ENGINEERING\matlap coding\lecture3\Book1.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 04-Dec-2024 18:20:58

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 51);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:AY50";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41", "VarName42", "VarName43", "VarName44", "VarName45", "VarName46", "VarName47", "VarName48", "VarName49", "VarName50", "VarName51"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
Book1 = readtable("C:\Users\ASUS\Desktop\NUMERICAL METHODS IN ENGINEERING\matlap coding\lecture3\Book1.xlsx", opts, "UseExcel", false);

%% Convert to output type
Book1 = table2array(Book1);

%% Clear temporary variables
clear opts